---
name: Build And Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        compiler: ['gcc']
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install compiler
        uses: rlalik/setup-cpp-compiler@master
        with:
          compiler: ${{ matrix.compiler }}
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: |
              3.7
              3.8
              3.9
              3.10
              3.11
      - name: Install Nox
        run: pip install nox
      - name: Run Tests
        run: nox --error-on-missing-interpreters -s test
