---
name: Build And Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-test:
    name: Run unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        compiler: ['gcc']
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install compiler
        uses: rlalik/setup-cpp-compiler@master
        with:
          compiler: ${{ matrix.compiler }}
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          # python-version-file does not seem to support multiple versions
          # definition
          python-version: |
            3.7
            3.8
            3.9
            3.10
            3.11
            3.12
          cache: pip
      - name: Install Nox
        run: pip install nox
      - name: Run Tests
        run: nox --error-on-missing-interpreters -s test -- --cov-report=xml:reports/coverage.xml --cov-append
      - name: Publish Coverage Results
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          directory: ./reports/
          files: ./coverage.xml
          flags: unittests
          name: pyitc
          token: ${{ secrets.CODECOV_TOKEN }}
  qa-test:
    name: Run QA tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        compiler: ['gcc']
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install compiler
        uses: rlalik/setup-cpp-compiler@master
        with:
          compiler: ${{ matrix.compiler }}
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          # python-version-file does not seem to support multiple versions
          # definition
          python-version: |
            3.7
            3.8
            3.9
            3.10
            3.11
            3.12
          cache: pip
      - name: Install Nox
        run: pip install nox
      - name: Check formatting
        run: nox --error-on-missing-interpreters -s format -- --check
      - name: Check linting
        run: nox --error-on-missing-interpreters -s lint
      - name: Check types
        run: nox --error-on-missing-interpreters -s typeCheck
